const ACTION_TYPES = {
   GET_DATA: "GET_DATA",
   SEARCH_NAME: "SEARCH_NAME",
   FILTER_HOSPITAL: "FILTER_HOSPITAL",
   FILTER_SPECIALIZATION: "FILTER_SPECIALIZATION",
   SET_LOADING: "SET_LOADING",
};

const ENDPOINT = {
   MAIN: "https://run.mocky.io/v3/c9a2b598-9c93-4999-bd04-0194839ef2dc",
};

export { ACTION_TYPES, ENDPOINT };
